### ISSUE TITLE
The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize()

### ISSUE THREAD

**Issue by sm-tester** [zonble/flutter_facebook_appevents#1]
Hi, every time when I call to  **"FacebookAppEvents.logEvent"** I get following error in debug log:
```
E/flutter (14484): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first., null)
E/flutter (14484): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14484): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (14484): <asynchronous suspension>
E/flutter (14484): #2      FacebookAppEvents.logEvent (package:flutter_facebook_appevents/src/flutter_facebook_appevents.dart:24:20)
E/flutter (14484): <asynchronous suspension>
E/flutter (14484): #3      ItemDetailsState.sendItemDetFBEvent (package:joyla/components/items/items_list.dart:528:21)
E/flutter (14484): <asynchronous suspension>
E/flutter (14484): #4      ItemDetailsState.regView (package:joyla/components/items/items_list.dart:523:3)
E/flutter (14484): <asynchronous suspension>
E/flutter (14484): #5      ItemDetailsState.initState (package:joyla/components/items/items_list.dart:558:3)
E/flutter (14484): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (14484): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (14484): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (14484): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (14484): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (14484): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (14484): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (14484): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (14484): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (14484): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (14484): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (14484): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (14484): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (14484): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (14484): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (14484): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (14484): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (14484): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (14484): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (14484): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (14484): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (14484): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (14484): #43     Element.updat
```

**Comment by zonble** [comment]
Please take a look at your "AndroidManifest.xml" file, and see if these following lines are included

``` xml
<meta-data
    android:name="com.facebook.sdk.AutoInitEnabled"
    android:value="true" />
```
